export interface Pedidos {
  id: number,
  produtos: string,
  valor: number,
  desconto: number,
  frete: number,
  rua: string,
  estado: string,
  cidade: string,
  numero: string,
  telefone: number,
  cep: number,
  complemento: string,
  image: string,
  opg_id: number,
  opg:string,
  user_id: number,
  user:string,
  cupom_id: number,
  cupom:string,
  cliente_id:number,
  cliente:string,
  emissao:string
}
