export interface Produto {
  id:number,
  nome: string,
  descricao: string,
  marca_id:number,
  marca: string,
  categoria_id: number,
  categoria: string,
  promocao_id:number,
  promocao: string,
  promo:boolean,
  favorito_id: number,
  semelhante_id: number,
  semelhante: string,
  cor_id:number,
  cor:string,
  tamanho_id:number,
  tamanho:string,
  subcategoria_id:number,
  subcategoria:string,
  preco: number,
  quantidade: number,
  vendidos: number,
  avalicao: number,
  image_principal: string,
  images: string,
  promocaoValor: number
}
